### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/babashka#18]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/babashka/issues/9)
- [ ] [Add key features](https://github.com/exercism/babashka/issues/10)
- [x] [Add tags](https://github.com/exercism/babashka/issues/11)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/babashka/issues/12)
- [ ] [Update status of track](https://github.com/exercism/babashka/issues/16)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/babashka/issues/17)
- [ ] [Pass linting checks](https://github.com/exercism/babashka/issues/13)
- [ ] [Build Test Runner](https://github.com/exercism/babashka/issues/14)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/babashka/issues/15) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
